### Znalezienie wszystkich zwierząt
GET http://localhost:8080/api/pets

### Znalezienie konkretnego zwierzęcia
GET http://localhost:8080/api/pets/1

### Stworzenie nowego zwierzęcia
POST http://localhost:8080/api/pets
Content-Type: application/json

{
  "name": "Axel",
  "birthdate": "2020-02-28",
  "type": "DOG"
}

### Wyszukanie zwierzęcia
GET http://localhost:8080/api/pets?name=ax
